CREATE TABLE Seller
(
    id              int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      varchar(255) not null,
    last_name       varchar(255) not null,
    patronymic_name varchar(255) not null,
    username        varchar(255) not null unique,
    password        varchar(255) not null,
    email           varchar(255) not null,
    phone           varchar(255) not null,
    is_deleted      boolean      not null default false
);

CREATE TABLE Category
(
    id         int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) not null,
    is_deleted boolean      not null default false
);

CREATE TABLE Product
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(255) not null,
    description varchar(255) not null,
    price       int          not null,
    count       int          not null,
    seller_id int REFERENCES Seller (id) ON DELETE CASCADE,
    category_id int REFERENCES Category (id) ON DELETE CASCADE,
    image       varchar(255) not null,
    is_deleted  boolean      not null default false
);

CREATE TABLE Orders
(
    id          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id   int          REFERENCES Seller (id) ON DELETE SET NULL,
    status      varchar(255) not null,
    goods_total int          not null,
    create_dt   date         not null,
    is_deleted  boolean      not null default false
);

CREATE TABLE Item
(
    code       int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id int REFERENCES Product (id),
    order_id   int REFERENCES Orders (id),
    count      int     not null,
    is_deleted boolean not null default false
);

CREATE TABLE ENTITY_CHANGE_LOG
(
    ID          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ENTITY_ID   int          not null,
    CHANGE_TYPE varchar(255) not null,
    CHANGE_DATE DATE         not null
);
